---
- hosts: k8s-master
  become: true
  tasks:

- name: Download Networking Script 
    when: inventory_hostname in groups['k8s-master']
    get_url:
      url: https://raw.githubusercontent.com/flinty1970/Kubernetes_Lab/main/networking.sh 
      dest: /tmp/networking.sh

- name: Running Networking Script 
    when: inventory_hostname in groups['k8s-master']
    command: "sh /tmp/networking.sh"

  - name: Remove file networking.sh
    ansible.builtin.file:
      path: /tmp/networking.sh
      state: absent
