---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iscsiplugin-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: manual
  selector:
    matchExpressions:
      - key: name
        operator: In
        values: ["data-iscsiplugin"]
